- name: Restart uWSGI
  supervisorctl: name=uwsgi state=restarted
  become: yes
  become_user: root

- name: Restart Celery worker
  become: yes
  become_user: root
  supervisorctl: name=celery-worker state=restarted
  when: celery

- name: Restart Celery beat
  become: yes
  become_user: root
  supervisorctl: name=celery-beat state=restarted
  when: celery

- name: Restart Nginx
  become: yes
  become_user: root
  service: name=nginx state=restarted

# Override broken Stouts.nginx handler, as it doesn't run as root
- name: Reload Nginx
  become: yes
  become_user: root
  service: name=nginx state=reloaded
