---
# file: roles/postfix_mandrill/handlers/main.yml

- name: Restart Postfix
  service: name=postfix state=restarted
  become: yes
  become_user: root
  notify:
    - Notification email
  ignore_errors: True
