language: python

cache:
  directories:
    # /home/travis/.cache/pip/wheels is the normal pip cache folder
    - $HOME/.cache/pip

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - pip install -U pip
  - pip install -r requirements.txt

script:
  - py.test

# Show version pinnings when the build as still succeeding
after_script:
  - pip freeze

# Update coverage information in codecov.io
after_success:
  - codecov

