# http://stackoverflow.com/a/30789043/315168
---
- name: Install dependencies
  become: yes
  become_user: root
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    acl

- name: Make sure sudoed users get access to SSH agent authentication socket
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep += "SSH_AUTH_SOCK"

# SSH_AUTH_SOCK access rights must be re-updated for every playbook run
# http://serverfault.com/a/442099/74975
- name: Enable SSH agent forwarding for wsgi user
  become: yes
  become_user: root
  shell: setfacl -m u:wsgi:rw $SSH_AUTH_SOCK && setfacl -m u:wsgi:x $(dirname $SSH_AUTH_SOCK)
  tags: site-update

- name: Make sure we actually got the access SSH_AUTH_SOCK access rights. If this fails it means SSH is reconnecting and ControlPersist option is missing.
  become: yes
  become_user: wsgi
  shell: ls $SSH_AUTH_SOCK
  tags: site-update

# TODO: Replace these with https://github.com/bfmartin/ansible-sshknownhosts
- name: Ensure github.com is a known host
  become: yes
  become_user: wsgi
  lineinfile:
    dest: /home/wsgi/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Ensure bitbucket.org is a known host
  become: yes
  become_user: wsgi
  lineinfile:
    dest: /home/wsgi/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
    regexp: "^bitbucket\\.org"

- name: Make sure we give rights to SSH_AUTH_SOCK on wsgi user on interactive SSH login
  become: yes
  become_user: "{{ ansible_user }}"
  lineinfile:
    line: "if [ ! -z '$SSH_AUTH_SOCK' ] ; then sudo setfacl -m u:wsgi:rw $SSH_AUTH_SOCK && sudo setfacl -m u:wsgi:x $(dirname $SSH_AUTH_SOCK) ; fi"
    regexp: "sudo setfacl"
    dest: "/home/{{ ansible_user }}/.bashrc"
    create: yes
    state: present
