---
# file: roles/postfix_mandrill/tasks/main.yml

- name: debconf-set-selections mailname for postfix
  shell: executable=/bin/bash debconf-set-selections <<< "postfix postfix/mailname string {{ ansible_hostname }}.{{ postfix_domain }}"
  tags: postfix

- name: debconf-set-selections mailer type for postfix
  shell: executable=/bin/bash debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
  tags: postfix

- name: install postfix via apt
  apt: pkg={{ item }} update_cache=yes
  with_items:
     - heirloom-mailx
     - postfix
     - mailutils
     - libsasl2-2
     - libsasl2-modules
     - ca-certificates
  tags: postfix

- name: Forward root user email to {{ notify_email }}
  shell: creates=~/.forward chdir=~ echo "{{ notify_email }}" > .forward
  tags: postfix

- name: Forward {{ ansible_env.USER }} user email to {{ notify_email }}
  sudo: false
  shell: creates=~/.forward chdir=~ echo "{{ notify_email }}" > .forward
  tags: postfix

- name: Copy disk-usage-alert script to /etc/cron.hourly (emails when disk full)
  template: src=disk-usage-alert.sh dest=/etc/cron.hourly/disk-usage-alert owner=root group=root mode=755
  tags: postfix

- name: Configure unattended upgrades in /etc/apt/apt.conf.d/50unattended-upgrades (emails upon upgrade failure)
  template: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades
  tags: postfix