# http://ryaneschinger.com/blog/securing-a-server-with-ansible/
- name: Install hardening application packages
  become: yes
  become_user: root
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
      - ufw
      - fail2ban
      - unattended-upgrades
