# http://ryaneschinger.com/blog/securing-a-server-with-ansible/
- name: Install hardening application packages
  become: yes
  become_user: root
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
      - ufw
      - fail2ban
      - unattended-upgrades

- name: Allow inboud SSH
  action: shell ufw allow 22/tcp

- name: Allow inbound HTTP
  action: shell ufw allow 80/tcp

- name: Allow inboud HTTPS
  action: shell ufw allow 443/tcp

- name: Enable firewall
  action: shell echo 'y' | ufw enable