# http://ryaneschinger.com/blog/securing-a-server-with-ansible/
- name: Install securing server software
  become: yes
  become_user: root
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
      - ufw
      - fail2ban
      - unattended-upgrades
      - logwatch


# Enable logwatch
# http://ryaneschinger.com/blog/securing-a-server-with-ansible/
- name: Email log summary daily
  lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ notify_email }} --detail high"
              state=present create=yes

- name: Allow inboud SSH
  action: shell ufw allow 22/tcp

- name: Allow inbound HTTP
  action: shell ufw allow 80/tcp

- name: Allow inboud HTTPS
  action: shell ufw allow 443/tcp

- name: Enable firewall
  action: shell echo 'y' | ufw enable