- name: Install Thawte Premium Server SSL certificates needed for encrypted SMTP
  shell: creates=/etc/postfix/cacert.pem cat /etc/ssl/certs/Thawte_Premium_Server_CA.pem | tee /etc/postfix/cacert.pem
  tags: postfix
  become: yes
  become_user: root

- name: Configure Postfix accounts
  lineinfile: dest=/etc/postfix/main.cf regexp='{{ item.regexp }}' line='{{ item.line }}'
  with_items:
    - { line: 'smtp_sasl_auth_enable = yes', regexp: '^smtp_sasl_auth_enable' }
    - { line: 'smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd', regexp: '^smtp_sasl_password_maps' }
    - { line: 'smtp_sasl_security_options = noanonymous', regexp: '^smtp_sasl_security_options' }
    - { line: 'smtp_use_tls = yes', regexp: '^smtp_use_tls' }
    - { line: "mydomain = {{ server_email_domain }}", regexp: '^mydomain' }
    - { line: "myhostname = {{ server_email_domain }}", regexp: '^myhostname' }
    - { line: "inet_interfaces = 127.0.0.1", regexp: '^inet_interfaces' }
  tags: postfix
  become: yes
  become_user: root
  notify:
    - Restart Postfix

- name: Configure outbound SMTP as Postfix's relayhost
  lineinfile: dest=/etc/postfix/main.cf regexp='^relayhost = ' line='relayhost = [{{ smtp_server }}]:{{ smtp_port }}'
  notify:
    - Restart Postfix
  tags: postfix
  become: yes
  become_user: root

- name: Setup credentials for outbout SMTP
  template: src=sasl_passwd dest=/etc/postfix/sasl_passwd owner=root group=root mode=600
  tags: postfix
  become: yes
  become_user: root
  notify:
    - Restart Postfix

- name: Run postmap to configure Postfix username lookup tables
  command: postmap /etc/postfix/sasl_passwd
  tags: postfix
  become: yes
  become_user: root
