---
# Run any migrations before performing full git pull and checkout.
# Full checkout would break existing running application because loading .py files
# with models for which database tables do not exist.

# TODO: Make this configurable, smarter.
# Only do backup when migrations have changed.
- name: Backup SQL database before migrations
  become: yes
  become_user: wsgi
  shell: "{{deploy_location}}/venv/bin/ws-dump-db {{ websauna_config_file }} > /home/wsgi/site.sql  chdir={{ deploy_location }}"
  when: db_backup_dump_before_migration == True

# TODO
- name: Fetch latest Alembic scripts from Git remote master for migrations
  become: yes
  become_user: wsgi
  shell: cd {{ deploy_location }} && git fetch && git checkout origin -- alembic

# Automatically run site migration scripts if any unrun scripts
- name: Run Alembic migrations
  become: yes
  become_user: wsgi
  command: "{{deploy_location}}/venv/bin/ws-alembic -c {{ websauna_config_file }} upgrade head chdir={{ deploy_location }}"