---
- name: Install dependencies
  become: yes
  become_user: root
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - supervisor
    - build-essential
    - libfreetype6-dev
    - libncurses5-dev
    - libxml2-dev
    - libxslt1-dev
    - libjpeg-dev
    - libpng12-dev
    - fail2ban
    - gettext
    - duplicity
    - python-boto
    - python-virtualenv
    - libpq-dev

- name: Create /srv/pyramid
  become: yes
  become_user: root
  file: path=/srv/pyramid state=directory

- name: Create a deploy location
  become: yes
  become_user: root
  file: path={{ deploy_location }} state=directory group=wsgi owner=wsgi mode="u=rwx,g=,o="

# Check if we have an already running site
- name: Check previous project checkouts
  stat: path={{ deploy_location }}/venv/bin/ws-backup
  register: previous_checkout
  become: yes
  become_user: wsgi

- name: Check we have correct Websauna install
  stat: path={{deploy_location}}/venv/bin/ws-dump-db
  register: previous_websauna
  become: yes
  become_user: wsgi

# Full checkout would break existing running application because loading .py files
# with models for which database tables do not exist
- name: "Run database migrations prior code update"
  include: premigrations.yml
  when: previous_checkout.stat.exists == True and previous_websauna.stat.exists == True

- name: Deploy Websauna application from a Git repository
  become: yes
  become_user: wsgi
  git: repo={{ git_repository }} dest={{deploy_location}} accept_hostkey=yes force=yes track_submodules=yes recursive=yes version={{ git_branch }}

- name: Create logs folder
  become: yes
  become_user: wsgi
  file: path={{ deploy_location }}/logs state=directory

- name: Create notebooks folder
  become: yes
  become_user: wsgi
  file: path={{ pyramid_notebook_notebook_folder }} state=directory

- name: Deploy INI config
  become: yes
  become_user: wsgi
  template: src=production.ini dest={{ deploy_location }}/conf/{{ site_mode }}.ini

- name: Deploy site secrets
  become: yes
  become_user: wsgi
  template: src={{ ini_secrets_file }} dest={{ deploy_location }}/conf/{{ site_mode }}-secrets.ini

- name: Check existence of virtualenv
  stat: path={{ deploy_location }}/venv
  register: has_virtualenv
  become: yes
  become_user: root

- name: Upgrade virtualenv to bugfixed versions
  become: yes
  become_user: root
  shell: pip install -U virtualenv

- name: Create virtualenv for app using chosen Python
  when: has_virtualenv.stat.exists == False
  shell: virtualenv --python={{ python_interpreter }} {{deploy_location}}/venv
  become: yes
  become_user: wsgi

- name: Activate virtualenv on login
  become: yes
  become_user: wsgi
  lineinfile: dest=/home/{{ wsgi_user }}/.profile regexp='^source /srv' line='source {{ deploy_location }}/venv/bin/activate'

- name: Enter to deployment directory on login
  become: yes
  become_user: wsgi
  lineinfile: dest=/home/{{ wsgi_user }}/.profile regexp='^cd /srv' line='cd {{ deploy_location }}'

- name: Install Python packages
  become: yes
  become_user: wsgi
  pip: requirements={{deploy_location}}/requirements.txt virtualenv={{deploy_location}}/venv

- name: Install application package
  become: yes
  become_user: wsgi
  command: "{{deploy_location}}/venv/bin/pip install -e {{deploy_location}}"

- name: Install uWSGI
  become: yes
  become_user: wsgi
  pip: name=uwsgi version={{ uwsgi_version }} virtualenv={{deploy_location}}/venv

# Now run un-run migrations unconditionally regardless if we
# are a prisitine or already running site
- name: Run migrations after codebase update and for pristine sites
  include: postmigrations.yml

# If migrations somehow still fail now it's good time to start screaming
- name: Perform database sanity check
  become: yes
  become_user: wsgi
  command: "{{ deploy_location }}/venv/bin/ws-sanity-check conf/{{ site_mode }}.ini chdir={{ deploy_location }}"

- name: Collect static files
  become: yes
  become_user: wsgi
  command: "{{ deploy_location }}/venv/bin/ws-collect-static conf/{{ site_mode }}.ini chdir={{ deploy_location }}"

- name: Deploy SSL certificates
  include: certificates.yml

- name: Deploy htpasswd passwords to protect Nginx
  htpasswd: "path=/etc/nginx/protected.htpasswd name={{ htpasswd_user }} password={{ htpasswd_password }} owner=root group=www-data mode=0640"
  when: htpasswd_password is defined
  become: yes
  become_user: root

- name: Deploy uWSGI config
  become: yes
  become_user: wsgi
  template: "src=uwsgi.ini dest={{ deploy_location }}/conf/uwsgi.ini"

- name: Deploy WSGI hander
  become: yes
  become_user: wsgi
  template: "src=pyramid.wsgi dest={{ deploy_location }}/conf/pyramid.wsgi"

- name: Deploy supervisor config
  become: yes
  become_user: root
  template: src=supervisor.conf dest=/etc/supervisor/conf.d/site.conf

- name: Deploy Nginx configuration
  become: yes
  become_user: root
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/default
  notify:
    - nginx restart

# TODO: Graceful uWSGI loading
# https://uwsgi-docs.readthedocs.org/en/latest/articles/TheArtOfGracefulReloading.html#standard-default-boring-graceful-reload-aka-sighup
- name: Start uWSGI
  become: yes
  become_user: root
  supervisorctl: name=uwsgi state=restarted

- name: Start Celery worker process
  become: yes
  become_user: root
  supervisorctl: name=celery-worker state=restarted

- name: Start Celery beat process
  become: yes
  become_user: root
  supervisorctl: name=celery-beat state=restarted



