# NOTE: ansible_product_version is different from Ansible Python package version
- name: Fail if Ansible is old
  fail:
    msg: "We have only tested with Ansible version 1.2+. Please update Ansible"
  when: ansible_product_version < '1.2'
  tags: site-update

- name: Fail if deploy_location not set
  fail:
   msg: Looks like deploy_location variable is not set. Have you configured your playbook properly?
  when: deploy_location is not defined
  tags: site-update

- name: Fail if SSH agent forward is not in use
  fail:
   msg: The Ansible server connection did not have SSH agent forwarding enabled.
  when: "'SSH_AUTH_SOCK' not in ansible_env"
  tags: site-update

- name: Fail if site mode is not set or is something we don't feel confident about
  fail:
    msg: "Could not read Ansible site_mode variable. It usually means that you have not configured required variables for this playbook, or you are including YAML variable files in wrong order."
  when: "site_mode not in ['production', 'staging']"
  tags: ["site-update", "site"]
  become: no

# TODO: For some reason the following gives unknown SSH error on Vagrant
- name: Check for local production-settings.ini
  local_action: "stat path={{ ini_secrets_file }}"
  register: ini_secrets_file_stat
  tags: site-update
  when: "ansible_env.USER != 'vagrant'"

- name: Fail if we cannot find the INI secrets file
  fail:
   msg: Please fill in ini_secrets_file setting - file not found
  when: "ansible_env.USER != 'vagrant' and ini_secrets_file_stat.stat.exists == false"
  connection: local
  tags: site-update

# If this happens your inbox gets hundreds of warnings due to sudo warning and logwatch during Ansible run
- name: Make sure sudo doesn't cause warnings on AWS due to unresolvable hostname
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/hosts
    create: no
    state: present
    line: "127.0.0.1 {{ ansible_hostname }}"
    regexp: "{{ ansible_hostname }}"
