# NOTE: ansible_product_version is different from Ansible Python package version
- name: Fail if Ansible is old
  fail:
    msg: "We have only tested with Ansible version 1.2+. Please update Ansible"
  when: ansible_product_version < '1.2'
